from __future__ import annotations

from dataclasses import asdict, dataclass, field
import importlib.util
import json
from pathlib import Path
from typing import Any

from slideforge.schemas import HtmlDeck, HtmlSlide
from slideforge.pptx_delivery_gate import ToolAvailability


@dataclass(frozen=True)
class PptxRendererEvidence:
    """Records whether an already-installed PPTX renderer can provide evidence."""

    strategy: str
    status: str
    tool: dict[str, Any]
    blockers: list[str] = field(default_factory=list)
    evidence_claim: str = "availability_only_no_visual_render_performed"

    @classmethod
    def detect(cls) -> "PptxRendererEvidence":
        tool = ToolAvailability.detect("pptx_glimpse", "pptx-glimpse")
        if tool.available:
            return cls(
                strategy="pptx_glimpse_available_for_renderer_evidence",
                status="available",
                tool=asdict(tool),
                blockers=[],
            )
        return cls(
            strategy="pptx_glimpse_required_for_renderer_evidence",
            status="unavailable",
            tool=asdict(tool),
            blockers=["Renderer evidence requires approved pptx-glimpse installation; no install was performed."],
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "strategy": self.strategy,
            "status": self.status,
            "tool": self.tool,
            "blockers": self.blockers,
            "evidence_claim": self.evidence_claim,
        }


def python_pptx_available() -> bool:
    return importlib.util.find_spec("pptx") is not None


def export_pptx_report(
    deck: HtmlDeck,
    output_path: str | Path,
    report_output: str | Path,
    run_id: str = "",
) -> dict[str, Any]:
    """Export a minimal native PPTX when python-pptx is installed, otherwise report honestly.

    python-pptx is intentionally imported only after this function establishes that
    the optional dependency is available. Missing dependency is a valid evidence
    outcome for no-install environments and does not create a fake PPTX.
    """

    output = Path(output_path)
    report_path = Path(report_output)
    renderer = PptxRendererEvidence.detect()

    if not python_pptx_available():
        blockers = ["dependency_missing: install the optional 'pptx' extra to enable python-pptx generation."]
        if output.exists():
            blockers.append("stale_output_path_exists: existing PPTX was not generated by this run.")
        report = _base_report(
            deck=deck,
            output_path=output,
            report_path=report_path,
            run_id=run_id,
            status="unavailable",
            blockers=blockers,
            generation_claim="no_pptx_output_created_python_pptx_missing",
            renderer=renderer,
        )
        report["generated_this_run"] = False
        _write_report(report_path, report)
        return report

    asset_evidence: dict[str, Any] = {"embedded_asset_count": 0, "missing_asset_paths": []}
    try:
        asset_evidence = _export_with_python_pptx(deck, output)
    except ImportError as exc:
        report = _base_report(
            deck=deck,
            output_path=output,
            report_path=report_path,
            run_id=run_id,
            status="unavailable",
            blockers=[f"dependency_missing: python-pptx import failed: {exc}"],
            generation_claim="no_pptx_output_created_python_pptx_import_failed",
            renderer=renderer,
        )
        _write_report(report_path, report)
        return report
    except Exception as exc:
        report = _base_report(
            deck=deck,
            output_path=output,
            report_path=report_path,
            run_id=run_id,
            status="unavailable",
            blockers=[f"pptx_generation_failed: {type(exc).__name__}: {exc}"],
            generation_claim="no_pptx_output_created_generation_failed",
            renderer=renderer,
        )
        _write_report(report_path, report)
        return report

    exists = output.exists()
    report = _base_report(
        deck=deck,
        output_path=output,
        report_path=report_path,
        run_id=run_id,
        status="available" if exists else "unavailable",
        blockers=[] if exists else ["pptx_generation_failed: output file was not created."],
        generation_claim=(
            "pptx_generated_with_python_pptx_static_evidence_only" if exists else "no_pptx_output_created"
        ),
        renderer=renderer,
    )
    report["output_exists"] = exists
    report["output_file_size_bytes"] = output.stat().st_size if exists else 0
    report["slide_count_generated"] = len(deck.slides) if exists else 0
    report["generated_this_run"] = exists
    report.update(asset_evidence)
    _write_report(report_path, report)
    return report


def _base_report(
    deck: HtmlDeck,
    output_path: Path,
    report_path: Path,
    run_id: str,
    status: str,
    blockers: list[str],
    generation_claim: str,
    renderer: PptxRendererEvidence,
) -> dict[str, Any]:
    return {
        "report_kind": "pptx_export",
        "run_id": run_id,
        "status": status,
        "generation_claim": generation_claim,
        "dependency": {
            "name": "python-pptx",
            "module": "pptx",
            "available": python_pptx_available(),
            "optional_extra": "pptx",
        },
        "deck_title": deck.title,
        "output_path": str(output_path),
        "report_output": str(report_path),
        "output_exists": output_path.exists(),
        "output_file_size_bytes": output_path.stat().st_size if output_path.exists() else 0,
        "slide_count_expected": len(deck.slides),
        "slide_count_generated": 0,
        "generated_this_run": False,
        "static_evidence": {
            "checks": [
                "output path recorded",
                "output existence recorded",
                "output byte size recorded",
                "expected/generated slide counts recorded",
            ]
        },
        "renderer_evidence": renderer.to_dict(),
        "blockers": blockers + renderer.blockers,
    }


def _write_report(path: Path, report: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _export_with_python_pptx(deck: HtmlDeck, output: Path) -> dict[str, Any]:
    from pptx import Presentation  # type: ignore[import-not-found]
    from pptx.dml.color import RGBColor  # type: ignore[import-not-found]
    from pptx.enum.text import PP_ALIGN  # type: ignore[import-not-found]
    from pptx.util import Inches, Pt  # type: ignore[import-not-found]

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    blank = prs.slide_layouts[6]
    total = len(deck.slides)
    embedded_asset_count = 0
    missing_asset_paths: list[str] = []

    for index, source in enumerate(deck.slides, start=1):
        slide = prs.slides.add_slide(blank)
        _add_background(slide, prs, RGBColor)
        _add_textbox(slide, source.title, Inches(0.7), Inches(0.74), Inches(6.7), Inches(1.0), Pt(32), bold=True)
        if source.subtitle:
            _add_textbox(slide, source.subtitle, Inches(0.74), Inches(1.55), Inches(6.8), Inches(0.45), Pt(16), color="9EB6CC")
        _add_textbox(slide, f"{index:02d} / {total:02d}", Inches(0.74), Inches(0.35), Inches(1.8), Inches(0.28), Pt(10), color="35E7FF", bold=True)
        embedded, missing = _add_generated_asset_image(slide, source, output.parent, Inches)
        embedded_asset_count += embedded
        missing_asset_paths.extend(missing)
        _add_archetype_content(slide, source, Inches, Pt, PP_ALIGN, RGBColor)

    output.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(output))
    return {"embedded_asset_count": embedded_asset_count, "missing_asset_paths": missing_asset_paths}


def _add_background(slide: Any, prs: Any, rgb_color: Any) -> None:
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = rgb_color(2, 3, 10)
    shape = slide.shapes.add_shape(1, 0, 0, prs.slide_width, prs.slide_height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = rgb_color(10, 18, 36)
    shape.fill.transparency = 18
    shape.line.fill.background()


def _add_textbox(
    slide: Any,
    text: str,
    left: Any,
    top: Any,
    width: Any,
    height: Any,
    size: Any,
    color: str = "F7FBFF",
    bold: bool = False,
) -> Any:
    box = slide.shapes.add_textbox(left, top, width, height)
    frame = box.text_frame
    frame.clear()
    paragraph = frame.paragraphs[0]
    run = paragraph.add_run()
    run.text = text
    run.font.name = "Malgun Gothic"
    run.font.size = size
    run.font.bold = bold
    run.font.color.rgb = _hex_rgb(color)
    return box


def _add_archetype_content(slide: Any, source: HtmlSlide, inches: Any, pt: Any, pp_align: Any, rgb_color: Any) -> None:
    if source.archetype in {"timeline"}:
        _add_timeline(slide, source, inches, pt)
    elif source.archetype in {"kpi_table", "table"}:
        _add_metrics(slide, source, inches, pt)
    elif source.archetype in {"chart", "bar_chart"}:
        _add_chart(slide, source, inches, pt, rgb_color)
    elif source.archetype in {"comparison_matrix", "matrix"}:
        _add_comparison(slide, source, inches, pt)
    elif source.archetype in {"cover", "visual_band", "architecture_visual"}:
        _add_visual_chips(slide, source, inches, pt)
    else:
        _add_bullets(slide, source.bullets, inches(0.9), inches(2.25), inches(7.2), inches(4.1), pt(18))


def _add_generated_asset_image(slide: Any, source: HtmlSlide, base_dir: Path, inches: Any) -> tuple[int, list[str]]:
    if source.archetype not in {"cover", "visual_band", "architecture_visual"} or not source.asset_path:
        return 0, []
    asset = Path(source.asset_path)
    resolved = asset if asset.is_absolute() else base_dir / asset
    if not resolved.exists():
        return 0, [source.asset_path]
    slide.shapes.add_picture(str(resolved), inches(7.15), inches(1.75), width=inches(5.35), height=inches(3.25))
    return 1, []


def _add_bullets(slide: Any, bullets: list[str], left: Any, top: Any, width: Any, height: Any, size: Any) -> None:
    if not bullets:
        return
    box = slide.shapes.add_textbox(left, top, width, height)
    frame = box.text_frame
    frame.clear()
    for index, bullet in enumerate(bullets):
        paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
        run = paragraph.add_run()
        run.text = bullet
        paragraph.level = 0
        run.font.name = "Malgun Gothic"
        run.font.size = size
        run.font.color.rgb = _hex_rgb("F7FBFF")


def _add_visual_chips(slide: Any, source: HtmlSlide, inches: Any, pt: Any) -> None:
    labels = [chip.label for chip in source.visual_chips] or source.bullets
    _add_bullets(slide, labels, inches(0.9), inches(2.25), inches(5.4), inches(3.8), pt(17))
    if not source.asset_path:
        _add_textbox(slide, "Visual asset placeholder / deterministic text overlay", inches(7.4), inches(4.7), inches(4.8), inches(0.5), pt(13), color="9EB6CC")


def _add_timeline(slide: Any, source: HtmlSlide, inches: Any, pt: Any) -> None:
    steps = source.timeline_steps
    labels = [f"{item.label}: {item.detail}" if item.detail else item.label for item in steps] or source.bullets
    _add_bullets(slide, labels, inches(0.9), inches(2.25), inches(10.8), inches(3.6), pt(16))


def _add_metrics(slide: Any, source: HtmlSlide, inches: Any, pt: Any) -> None:
    rows = [(row.label, row.value) for row in source.metric_rows] or [_split_pair(item) for item in source.bullets]
    _add_table(slide, [["Metric", "Value"], *rows], inches(0.9), inches(2.25), inches(8.4), inches(0.48), pt(13))


def _add_chart(slide: Any, source: HtmlSlide, inches: Any, pt: Any, rgb_color: Any) -> None:
    data = source.chart_data or []
    if not data:
        _add_bullets(slide, source.bullets, inches(0.9), inches(2.25), inches(7.2), inches(4.1), pt(18))
        return
    max_value = max((abs(item.value) for item in data), default=1) or 1
    top = inches(2.25)
    for idx, item in enumerate(data):
        y = top + inches(idx * 0.55)
        _add_textbox(slide, item.label, inches(0.9), y, inches(1.8), inches(0.3), pt(11))
        width = inches(4.4 * abs(item.value) / max_value)
        bar = slide.shapes.add_shape(1, inches(2.75), y, width, inches(0.25))
        bar.fill.solid()
        bar.fill.fore_color.rgb = rgb_color(53, 231, 255) if idx % 2 == 0 else rgb_color(255, 79, 216)
        bar.line.fill.background()
        _add_textbox(slide, f"{item.value:g}", inches(7.35), y, inches(0.9), inches(0.3), pt(11), color="35E7FF", bold=True)


def _add_comparison(slide: Any, source: HtmlSlide, inches: Any, pt: Any) -> None:
    columns = [column.label for column in source.comparison_columns]
    rows = source.comparison_rows
    if rows:
        table = [["Criteria", *columns], *[[row.label, *row.values] for row in rows]]
    else:
        table = [["Item", "Value"], *[_split_pair(item) for item in source.bullets]]
    _add_table(slide, table, inches(0.75), inches(2.2), inches(10.8), inches(0.42), pt(10))


def _add_table(slide: Any, data: list[list[str]], left: Any, top: Any, width: Any, row_height: Any, size: Any) -> None:
    if not data:
        return
    rows = len(data)
    cols = max(len(row) for row in data)
    shape = slide.shapes.add_table(rows, cols, left, top, width, row_height * rows)
    table = shape.table
    for row_idx, row in enumerate(data):
        for col_idx in range(cols):
            cell = table.cell(row_idx, col_idx)
            cell.text_frame.clear()
            paragraph = cell.text_frame.paragraphs[0]
            run = paragraph.add_run()
            run.text = row[col_idx] if col_idx < len(row) else "—"
            run.font.name = "Malgun Gothic"
            run.font.size = size
            run.font.bold = row_idx == 0
            run.font.color.rgb = _hex_rgb("F7FBFF" if row_idx else "35E7FF")


def _split_pair(text: str) -> list[str]:
    label, sep, value = text.partition("|")
    return [label.strip(), value.strip() if sep else "—"]


def _hex_rgb(value: str) -> Any:
    from pptx.dml.color import RGBColor  # type: ignore[import-not-found]

    clean = value.lstrip("#")
    return RGBColor(int(clean[0:2], 16), int(clean[2:4], 16), int(clean[4:6], 16))
