import json
from pathlib import Path

from slideforge.cli import main
from slideforge.evidence_summary import summarize_run


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def test_minimal_run_with_browser_plan_warns_real_browser_evidence_missing(tmp_path):
    run_dir = tmp_path / "run"
    run_dir.mkdir()
    (run_dir / "deck.html").write_text("<!doctype html><div class='slide'>안녕</div>", encoding="utf-8")
    _write_json(run_dir / "browser-regression-plan.json", {"report_kind": "browser_regression_plan"})

    summary = summarize_run(run_dir)

    assert summary["status"] == "needs_visual_evidence"
    assert summary["sections"]["html"]["status"] == "available"
    assert summary["sections"]["browser_capture"]["status"] == "not_captured"
    assert any("browser_capture_not_captured" in warning for warning in summary["warnings"])


def test_captured_browser_report_records_screenshot_count(tmp_path):
    run_dir = tmp_path / "run"
    (run_dir / "browser-capture").mkdir(parents=True)
    (run_dir / "deck.html").write_text("<!doctype html>", encoding="utf-8")
    _write_json(
        run_dir / "browser-capture" / "browser-regression-report.json",
        {
            "report_kind": "browser_regression_report",
            "screenshot_capture": {"status": "captured"},
            "slide_count_detected": 2,
            "screenshots": [{"path": "slide-01.png"}, {"path": "slide-02.png"}],
        },
    )

    summary = summarize_run(run_dir)

    assert summary["sections"]["browser_capture"]["status"] == "captured"
    assert summary["counts"]["browser_screenshots"] == 2
    assert summary["sections"]["browser_capture"]["screenshots"] == 2


def test_pptx_generated_this_run_false_blocker_not_final_visual_evidence(tmp_path):
    run_dir = tmp_path / "run"
    run_dir.mkdir()
    (run_dir / "deck.html").write_text("<!doctype html>", encoding="utf-8")
    _write_json(
        run_dir / "pptx-export-report.json",
        {
            "report_kind": "pptx_export",
            "status": "unavailable",
            "generation_claim": "no_pptx_output_created_python_pptx_missing",
            "output_exists": False,
            "slide_count_generated": 0,
            "generated_this_run": False,
            "renderer_evidence": {"status": "unavailable"},
            "blockers": ["stale_output_path_exists: existing PPTX was not generated by this run."],
        },
    )

    summary = summarize_run(run_dir)

    assert summary["status"] == "blocked"
    assert summary["sections"]["pptx"]["generated_this_run"] is False
    assert any("pptx_stale_output" in blocker for blocker in summary["blockers"])
    assert any("pptx_not_final_visual_evidence" in warning for warning in summary["warnings"])


def test_comfyui_unavailable_report_records_pending_not_deterministic_failure(tmp_path):
    run_dir = tmp_path / "run"
    run_dir.mkdir()
    (run_dir / "deck.html").write_text("<!doctype html>", encoding="utf-8")
    _write_json(
        run_dir / "comfyui-handoff-report.json",
        {
            "status": "unavailable",
            "server_available": False,
            "generated_assets": [],
            "pending_assets": [{"slide_id": "s1", "status": "pending"}],
            "failed_assets": [],
            "blockers": ["ComfyUI health check failed", "execution disabled; report records handoff contract only"],
        },
    )

    summary = summarize_run(run_dir)

    assert summary["sections"]["comfyui"]["status"] == "unavailable"
    assert summary["counts"]["comfyui_pending_assets"] == 1
    assert not any("comfyui" in blocker for blocker in summary["blockers"])
    assert any("comfyui_pending" in warning for warning in summary["warnings"])


def test_cli_writes_json_and_markdown_summary(tmp_path):
    run_dir = tmp_path / "run"
    run_dir.mkdir()
    (run_dir / "deck.html").write_text("<!doctype html>", encoding="utf-8")
    _write_json(
        run_dir / "browser-capture" / "browser-regression-report.json",
        {
            "screenshot_capture": {"status": "captured"},
            "slide_count_detected": 1,
            "screenshots": [{"path": "slide-01.png"}],
        },
    )
    output = run_dir / "summary.json"
    markdown = run_dir / "summary.md"

    exit_code = main([
        "summarize-run",
        "--run-dir",
        str(run_dir),
        "--output",
        str(output),
        "--markdown-output",
        str(markdown),
    ])

    assert exit_code == 0
    data = json.loads(output.read_text(encoding="utf-8"))
    assert data["report_kind"] == "run_evidence_summary"
    assert data["sections"]["browser_capture"]["status"] == "captured"
    text = markdown.read_text(encoding="utf-8")
    assert "# SlideForge run evidence summary" in text
    assert "## Browser capture" in text
    assert "## PPTX" in text
    assert "## ComfyUI" in text
